EmailHubApp/Controllers/FileController.cs
using AutoMapper;
using Azure;
using Azure.Core;
using EmailHubApp.Database;
using EmailHubApp.Manager;
using EmailHubApp.Manager.Contract;
using EmailHubApp.Model.Models;
using EmailHubApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Diagnostics;
using OfficeOpenXml;
using System.IO;
using System.Net;
using System.Runtime.InteropServices;
using System.Text.RegularExpressions;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
//using Excel = Microsoft.Office.Interop.Excel;

namespace EmailHubApp.Controllers
{
    public class FileController : Controller
    {
        #region Initialization
        private readonly EmailHubDB _db;
        private readonly IMapper _iMapper;
        private readonly IUserManager _iUserManager;
        private readonly ISearchQueryManager _iSearchQueryManager;
        private readonly ISearchedDataManager _iSearchedDataManager;
        private readonly ISearchRequirementsManager _iSearchRequirementsManager;
        public FileController(IMapper iMapper, IUserManager iUserManager, ISearchQueryManager iSearchQueryManager, ISearchedDataManager iSearchedDataManager, ISearchRequirementsManager iSearchRequirementsManager)
        {
            _db = new EmailHubDB();
            _iMapper = iMapper;
            _iUserManager = iUserManager;
            _iSearchQueryManager = iSearchQueryManager;
            _iSearchedDataManager = iSearchedDataManager;
            _iSearchRequirementsManager = iSearchRequirementsManager;
        }
        #endregion

        public IActionResult Index()
        { 
            try
            {
                #region Login Check
                if (HttpContext.Session.GetString("UserID") == "" || HttpContext.Session.GetString("UserID") == null)
                    return RedirectToAction("Login", "User");
                #endregion

                if(TempData["LimitEnd"]!= null)
                {
                    ViewBag.ErrorMessage = "You have reached your search limit. Please Upgrade your membership!";

                    if (TempData.TryGetValue("ResultData", out object? dataListObj))
                    {
                        if(dataListObj != null && dataListObj is string[] dataArray)
                        {
                            List<string> dataList = dataArray.ToList();
                            ViewBag.DataList = dataList;
                        }
                    }
                }
                else if (TempData["ResultData"] == null)
                {
                    ViewBag.ErrorMessage = "No Result Data Found!";
                }
                else if(TempData.TryGetValue("ResultData", out object? dataListObj))
                {
                    if (dataListObj != null && dataListObj is string[] dataArray)
                    {
                        List<string> dataList = dataArray.ToList();
                        ViewBag.DataList = dataList;
                    }
                    else
                    {
                        return BadRequest("No Data Found");
                    }
                }
                return View();
            }
            catch (Exception ex) 
            {
                ViewBag.ErrorMessage = ex.Message;
                return View();
            }
        }

        public IActionResult DownloadResult(List<string> Result)
        {
            try
            {
                #region Login Check
                if (HttpContext.Session.GetString("UserID") == "" || HttpContext.Session.GetString("UserID") == null)
                    return RedirectToAction("Login", "User");
                #endregion

                if (Result != null && Result.Count > 0)
                {
                    // Create a new Excel package
                    using (var package = new ExcelPackage())
                    {
                        // Add a new worksheet to the Excel package
                        var worksheet = package.Workbook.Worksheets.Add("Sheet1");

                        // Populate the Excel worksheet with data from the list
                        int i, j = 0;
                        for (i = 0; i <= Result.Count/2; i++)
                        {
                            if (i == 0)
                            {
                                worksheet.Cells[i + 1, 1].Value = "Search";
                                worksheet.Cells[i + 1, 2].Value = "Result";                              
                                continue;
                            }
                            worksheet.Cells[i + 1, 1].Value = Result[j];
                            worksheet.Cells[i + 1, 2].Value = Result[j+1];
                            j+=2;
                        }

                        // Set the content type and file name
                        var contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                        var fileName = $"ResultFile_{DateTime.Today.ToString("yyyyMMdd")}.xlsx";

                        // Convert the Excel package to a byte array
                        var fileBytes = package.GetAsByteArray();

                        // Return the Excel file as a file result
                        return File(fileBytes, contentType, fileName);
                    }
                }
                ViewBag.ErrorMessage = "Failed to Download!";
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View();
            }
        }

        #region Load Excel File
        public IActionResult LoadFile()
        {
            #region Login Check
            if (HttpContext.Session.GetString("UserID") == "" || HttpContext.Session.GetString("UserID") == null)
                return RedirectToAction("Login", "User");
            #endregion

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LoadFile(IFormFile file)
        {
            #region Login Check
            if (HttpContext.Session.GetString("UserID") == "" || HttpContext.Session.GetString("UserID") == null)
                return RedirectToAction("Login", "User");
            #endregion
        
            try
            {
                List<string> excelData = new List<string>();
                List<SearchedData> searchedDataList = new List<SearchedData>();

                if (file == null || file.Length == 0)
                {
                    ViewBag.ErrorMessage = "No File Uploaded";
                }
                else
                {
                    using (var stream = new MemoryStream()) 
                    {
                        await file.CopyToAsync(stream);

                        using (var package = new ExcelPackage(stream))
                        {
                            var worksheet = package.Workbook.Worksheets.FirstOrDefault();
                            if (worksheet == null) 
                            {
                                return BadRequest("The Excel file does not contain any worksheets.");
                            }

                            #region Fetch All data in a List String
                            string result = string.Empty;
                            int UsersearchedCount = Convert.ToInt32(HttpContext.Session.GetString("Searched"));

                            for (int row = 2; row <= worksheet.Dimension.Rows; row++)
                            {
                                if(HttpContext.Session.GetString("Membership") != "Admin" && Convert.ToInt32(HttpContext.Session.GetString("Limit")) <= UsersearchedCount)
                                {
                                    TempData["LimitEnd"] = "Limit End";                                    
                                    break;
                                }

                                var cellValue = worksheet.Cells[row, 1].Text;

/*Replace White Spaces*/
                                if (cellValue.Contains(' '))
                                {
                                    var cellValue2 = cellValue.Replace(" ", "");
                                    cellValue = cellValue2;
                                }

                                if (cellValue == null || cellValue == string.Empty)
                                {
                                    continue;
                                }

                                #region Get the result Data And add to the list String
                                result = string.Empty;

/*Clean Search site*/
                                cellValue = cellValue.ToLower();
                                cellValue = SiteCleaning(cellValue);

                                result = GetDataFromWeb(cellValue);

                                if (result == string.Empty || result == null)
                                {
                                    if (result == null)
                                        result = string.Empty;

                                    excelData.Add(cellValue);
                                    excelData.Add(result);
                                    continue;
                                }

                                SearchedData searchedData = new SearchedData();
                                searchedData.SearchedKey = cellValue;
                                searchedData.SearchedValue = result;
                                searchedData.UserID = Convert.ToInt32(HttpContext.Session.GetString("UserID"));
                                searchedData.SearchDate = DateTime.Today;

/*Do The check and counting*/
                                if (row % 50 == 0 || row >= worksheet.Dimension.Rows)
                                {

EmailHubApp/Views/File/DownloadResult.cshtml
@{
    ViewData["Title"] = "DownloadResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger"><strong>Error:&nbsp;</strong>@ViewBag.ErrorMessage</div>
}

EmailHubApp/Views/File/Index.cshtml
@model SearchedDataOperation
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger"><strong>Error:&nbsp;</strong>@ViewBag.ErrorMessage</div>
}
@if (ViewBag.DataList != null)
{
    <h2>Download Result Data</h2><hr />

    List<string> Result = ViewBag.DataList;
    int count = 0, serial = 1;

    if (Result!= null && Result.Count> 0)
    {
        count = Result.Count;

        <form asp-controller="File" asp-action="DownloadResult" method="post">
            <div>
                <table id="example" class="table table-striped nowrap" style="width:100%">
                    <thead>
                        <tr>
                            <th>Serial</th>
                            <th>Search Key</th>
                            <th>Result</th>
                        </tr>
                    </thead>
                    <tbody> 
                        @for (int i = 0; i < count; i += 2)
                        {
                            <tr>
                                <td>@(serial++)</td>
                                <td>@Result[i]</td>                                
                                <td>@Result[i+1]</td>

                                <input type="hidden" name="Result" value="@Result[i]" />
                                <input type="hidden" name="Result" value="@Result[i+1]" />
                            </tr>                           
                        }
                    </tbody>
                </table>
            </div>
            <button type="submit" class="btn btn-dark">Download</button>
        </form>
    }   
}

EmailHubApp/Views/File/LoadFile.cshtml
@{
    ViewData["Title"] = "LoadFile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger"><strong>Error:&nbsp;</strong>@ViewBag.ErrorMessage</div>
}
<form asp-controller="File" enctype="multipart/form-data" asp-action="LoadFile" method="post">
    <h2>Upload File</h2><hr />  
    <div >
        <article>Select File</article>
        <span class="mx-auto py-1 border border-secondary border-2"><input type="file" name="File" /></span><br /><br />
        <input type="submit" value=" Read Data " />
    </div>
    
</form>