EmailHubApp/Controllers/SecurityController.cs
using AutoMapper;
using EmailHubApp.Manager.Contract;
using EmailHubApp.Model.Models;
using EmailHubApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using Microsoft.Identity.Client;
using Microsoft.CodeAnalysis;
using EmailHubApp.Database;
using System.Dynamic;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;
using EmailHubApp.Manager;

namespace EmailHubApp.Controllers
{
    #region Admin Users Only
    public class SecurityController : Controller
    {
        #region Initialization
        private readonly EmailHubDB _db;
        private readonly IMapper _iMapper;    
        private readonly IUserManager _iUserManager;
        private readonly IUserTypeManager _iUserTypeManager;
        private readonly ISearchQueryManager _iSearchQueryManager;
        private readonly ISearchedDataManager _iSearchedDataManager;
        private readonly ISearchRequirementsManager _iSearchRequirementsManager;
        public SecurityController(IMapper iMapper, IUserManager iUserManager, IUserTypeManager iUserTypeManager, ISearchQueryManager iSearchQueryManager, ISearchedDataManager iSearchedDataManager, ISearchRequirementsManager iSearchRequirementsManager)
            {
                _db = new EmailHubDB();
                _iMapper = iMapper;
                _iUserManager = iUserManager;
                _iUserTypeManager = iUserTypeManager;
                _iSearchQueryManager = iSearchQueryManager;
                _iSearchedDataManager = iSearchedDataManager;
                _iSearchRequirementsManager = iSearchRequirementsManager;
            }
        #endregion

        #region User

        #region User List
        [HttpGet]
        public async Task<ActionResult<IEnumerable<UserOperation>>> Index()
        {
            try
            {
                #region Admin Check
                if (HttpContext.Session.GetString("Membership") != "Admin")
                    return StatusCode(403, "Access Denied: You don not have the permission to access this resource");
            #endregion

                if (TempData["ErrorMessage"] != null)
                {
                    string? message = TempData["ErrorMessage"] as string;
                    if (message != null)
                    {
                        ViewBag.ErrorMessage = message;
                        TempData["ErrorMessage"] = null;
                    }
                }

            IEnumerable<UserOperation> users = _iMapper.Map<IEnumerable<UserOperation>>(await _iUserManager.GetAll());

                ViewBag.userType = _iMapper.Map<IEnumerable<UserTypeOperation>>(await _iUserTypeManager.GetAll());

                return View(users);
            }
            catch(Exception ex)
            {
                return ViewBag.ErrorMessage = ex.Message;
            }
        }
        #endregion

        #region Create and Update User
        [HttpGet]
        public async Task<IActionResult> AddUpdateUser(int? id)
        {
            try
            {
                #region Admin Check
                if (HttpContext.Session.GetString("Membership") != "Admin")
                    return StatusCode(403, "Access Denied: You do not have the permission to access this resource");
                #endregion

                ViewBag.userType = _iMapper.Map<IEnumerable<UserTypeOperation>>(await _iUserTypeManager.GetAll());

                if (id == null)
                {
                    HttpContext.Session.SetString("Title", "Create");
                    return View();
                }

                HttpContext.Session.SetString("Title", "Update");

                UserOperation user = _iMapper.Map<UserOperation>(await _iUserManager.GetById(id));

                return View(user);
            }
            catch (Exception ex) 
            {
                return ViewBag.ErrorMessage(ex.Message);
            }            
        }

        [HttpPost]
        public async Task<IActionResult> AddUpdateUser(UserOperation user, string? confirm)
        {
            try
            {
                #region Admin Check
                if (HttpContext.Session.GetString("Membership") != "Admin")
                    return StatusCode(403, "Access Denied: You do not have the permission to access this resource");
                #endregion

                ViewBag.userType = _iMapper.Map<IEnumerable<UserTypeOperation>>(await _iUserTypeManager.GetAll());
                if (ModelState.IsValid) 
                {
                    User addupdateUser = _iMapper.Map<User>(user);                   
                    bool notValid = false;

                    #region New User Add
                    if (user.ID == 0)
                    {
                        #region Validation Check                       
                        bool usernameExists = _db.User.Any(u => u.UserName == user.UserName);
                        if (usernameExists)
                        {
                            ViewBag.UserNameExists = "UserName already exists!";
                            notValid = true;
                        }
                        bool emailExists = _db.User.Any(e => e.Email == user.Email);
                        if (emailExists)
                        {
                            ViewBag.EmailExists = "Email already exists!";
                            notValid = true;
                        }
                        if(addupdateUser.TypeID == 0)
                        {
                            ViewBag.NoUserTypeSelected = "Please Select a User Type!";
                            notValid = true;
                        }
                        if (user.Password != confirm)
                        {
                            ViewBag.PasswordMismatched = "Password is not matching!";
                            notValid = true;
                        }
                        if (notValid)
                        {
                            return View(user);
                        }
                        #endregion

                        addupdateUser.Password = EDPassword(user.Password, true);

                        addupdateUser.EntryDate = DateTime.Now;
                        addupdateUser.TotalSearched = 0;

                        bool isAdded = await _iUserManager.Create(addupdateUser);
                        if (isAdded)
                            return RedirectToAction("Index");
                        else
                            ViewBag.ErrorMessage = "Failed to Create New User";
                    }
                    #endregion

                    #region Old User Update
                    else
                    {
                        #region Validation Check                       
                        User? OldInfo = _db.User.Find(user.ID);
                            
                        if(OldInfo != null && OldInfo.UserName == "admin" && OldInfo.UserName != user.UserName)
                        {
                            ViewBag.UserNameExists = "\'admin\' UserID can't be Changed!";
                            notValid = true;
                        }
                        if (OldInfo != null && Convert.ToInt32(HttpContext.Session.GetString("UserID")) == user.ID && OldInfo.Name != user.Name)
                        {
                            HttpContext.Session.SetString("UserName", user.Name);
                        }
                    if (OldInfo!= null && OldInfo.UserName!= user.UserName)
                        {
                            int userNameCount = _db.User.Count(u => u.UserName == user.UserName);
                            if (userNameCount > 0) 
                            {
                                ViewBag.UserNameExists = "UserName already exists!";
                                notValid = true;
                            }
                        }
                        if (OldInfo != null && OldInfo.Email != user.Email)
                        {
                            int emailCount = _db.User.Count(u => u.Email == user.Email);
                            if (emailCount > 0)
                            {
                                ViewBag.EmailExists = "Email already exists!";
                                notValid = true;
                            }
                        }
                        if(OldInfo != null && Convert.ToInt32(HttpContext.Session.GetString("UserID")) == user.ID && OldInfo.TypeID != user.TypeID)
                        {
                            ViewBag.NoUserTypeSelected = "User Type of Logged in User can't be changed!";
                            notValid = true;
                        }
                        if (addupdateUser.TypeID == 0)
                        {
                            ViewBag.NoUserTypeSelected = "Please Select a User Type!";
                            notValid = true;
                        }                            
                        if(OldInfo != null && (confirm == "" || confirm == null))
                        {
                            user.Password = OldInfo.Password;
                        }
                        else if (user.Password != confirm)
                        {
                            ViewBag.ErrorMessage = "Password is not matching";
                            notValid = true;
                        }
                        if (notValid)
                        {
                            return View(user);
                        }
                        #endregion

                        addupdateUser.Password = EDPassword(user.Password, true);

                        bool isUpdated = await _iUserManager.Update(addupdateUser);
                        if (isUpdated)
                            return RedirectToAction("Index");
                        else

EmailHubApp/Views/Security/AddUpdateSearchQuery.cshtml
@using Microsoft.AspNetCore.Http
@using EmailHubApp.Models;
@model SearchQueryOperation
@{
    ViewData["Title"] = "AddUpdateSearchQuery";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger"><strong>Error:&nbsp;</strong>@ViewBag.ErrorMessage</div>
}
@{
    var title = Context.Session.GetString("Title");
}
<h2>@title Search-Query</h2>
<hr />
<br />
<div>
    <form method="post" asp-controller="Security" asp-action="AddUpdateSearchQuery">
        <div class="row">
            <div class="col-md-8">
                <div>
                    <label asp-for="Start" class="col-md-3">Start Part</label>
                    <input type="text" asp-for="Start" class="col-md-6" required="required" placeholder="Enter Start Part" />
                    <span asp-validation-for="Start" class="text-danger"></span><br />                    
                </div><br />

                <div>
                    <label asp-for="End" class="col-md-3">End Part</label>
                    <input type="text" asp-for="End" class="col-md-6" required="required" placeholder="Enter End Part" />
                    <span asp-validation-for="End" class="text-danger"></span><br />
                    @if (ViewBag.searchQueryExists != null)
                    {
                        <br />

                        <label class="col-md-3"></label>
                        <span style="color:red;">@ViewBag.searchQueryExists</span>
                    }
                </div><br />

                <div class="checkbox">
                    <label class="col-md-3"></label>
                    <label>
                        <input type="checkbox" asp-for="IsActive"> Active Search Query
                    </label>                    
                </div><br />
                <div>
                    <label class="col-md-3"></label>
                    @if (title == "Create")
                    {
                        <button type="submit" class="btn btn-success">Create</button>
                    }
                    else
                    {
                        <button type="submit" class="btn btn-primary">Update</button>
                    }
                    <a asp-controller="Security" asp-action="SearchQueryList" class="btn btn-secondary">Search Query List</a>
                </div>
            </div>
        </div>
    </form>
</div>

EmailHubApp/Views/Security/AddUpdateSearchRequirements.cshtml
@using Microsoft.AspNetCore.Http
@using EmailHubApp.Models;
@model SearchRequirementsOperation
@{
    ViewData["Title"] = "AddUpdateSearchRequirements";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger"><strong>Error:&nbsp;</strong>@ViewBag.ErrorMessage</div>
}
@{
    var title = Context.Session.GetString("Title");
}
<h2>@title Search-Requirement</h2>
<hr />
<br />
<div>
    <form method="post" asp-controller="Security" asp-action="AddUpdateSearchRequirements">
        <div class="row">
            <div class="col-md-8">
                <div>
                    <label asp-for="ApiKey" class="col-md-3">API Key</label>
                    <input type="text" asp-for="ApiKey" class="col-md-6" required="required" placeholder="Enter API Key" />
                    <span asp-validation-for="ApiKey" class="text-danger"></span><br />
                    @if (ViewBag.ApiKeyExists != null)
                    {
                        <label class="col-md-3"></label>
                        <span style="color:red;">@ViewBag.ApiKeyExists</span>
                    }
                </div><br />

                <div>
                    <label asp-for="CX" class="col-md-3">CX</label>
                    <input type="text" asp-for="CX" class="col-md-6" required="required" placeholder="Enter CX" />
                    <span asp-validation-for="CX" class="text-danger"></span><br />
                    @if (ViewBag.CxExists != null)
                    {
                        <label class="col-md-3"></label>
                        <span style="color:red;">@ViewBag.CxExists</span>
                    }
                </div><br />

                <div class="checkbox">
                    <label class="col-md-3"></label>
                    <label>
                        <input type="checkbox" asp-for="IsActive"> Active
                    </label>
                </div><br />
                <div>
                    <label class="col-md-3"></label>
                    @if (title == "Create")
                    {
                        <button type="submit" class="btn btn-success">Create</button>
                    }
                    else
                    {
                        <button type="submit" class="btn btn-primary">Update</button>
                    }
                    <a asp-controller="Security" asp-action="SearchRequirementsList" class="btn btn-secondary">Search-Requirements List</a>
                </div>
            </div>
        </div>
    </form>
</div>

EmailHubApp/Views/Security/AddUpdateUser.cshtml
@using Microsoft.AspNetCore.Http
@using EmailHubApp.Models;
@model UserOperation
@{
    ViewData["Title"] = "AddUpdateUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if(ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger"><strong>Error:&nbsp;</strong>@ViewBag.ErrorMessage</div>
}
@{
    var title = Context.Session.GetString("Title");
}
<h2>@title User</h2>
<hr />
<br />
<div>
    <form method="post" asp-controller="Security" asp-action="AddUpdateUser">
        <div class="row">
            <div class="col-md-8">
                <div>
                    <label asp-for="Name" class="col-md-3">Name</label>
                    <input type="text" asp-for="Name" class="col-md-6" required="required" placeholder="Enter User Name" />
                    <span asp-validation-for="Name" class="text-danger"></span><br />
                </div><br />

                <div>
                    <label asp-for="UserName" class="col-md-3">UserID</label>
                    <input type="text" asp-for="UserName" class="col-md-6" required="required" placeholder="Enter UserID" />
                    <span asp-validation-for="UserName" class="text-danger"></span><br />
                    @if (ViewBag.UserNameExists != null)
                    {
                        <label class="col-md-3"></label>
                        <span style="color:red;">@ViewBag.UserNameExists</span>
                    }
                </div><br />

                <div>
                    <label asp-for="Email" class="col-md-3">Email</label>
                    <input type="text" asp-for="Email" class="col-md-6" required="required" placeholder="Enter Email Address" />
                    <span asp-validation-for="Email" class="text-danger"></span><br />
                    @if (ViewBag.EmailExists != null)
                    {
                        <label class="col-md-3"></label>
                        <span style="color:red;">@ViewBag.EmailExists</span>
                    }
                </div><br />

                <div>
                    <label asp-for="TypeID" class="col-md-3">User Type</label>
                    <select asp-for="TypeID" class="col-md-6">
                        <option value=""><strong>--Select User Type--</strong></option>
                        @foreach (UserTypeOperation i in ViewBag.userType)
                        {
                            if(i.IsActive)
                            {
                                <option value="@i.ID">@i.Name</option>
                            }                          
                        }
                    </select>
                    <span asp-validation-for="TypeID" class="text-danger"></span>
                    @if (ViewBag.NoUserTypeSelected != null)
                    {
                        <label class="col-md-3"></label>
                        <span style="color:red;">@ViewBag.NoUserTypeSelected</span>
                    }
                </div><br />
                
                <div>
                    <label asp-for="Password" class="col-md-3">Password</label>
                    <input type="password" asp-for="Password" class="col-md-6" required="required" placeholder="Enter Password" />
                    <span asp-validation-for="Password" class="text-danger"></span><br />
                </div><br />

                <div>
                    <label class="col-md-3">Confirm Password</label>
                    <input type="password" name="confirm" class="col-md-6" placeholder="Confirm Password" />
                </div><br />
                <div class="checkbox">
                    <label class="col-md-3"></label>
                    <label>
                        <input type="checkbox" asp-for="IsActive"> Active User
                    </label>
                </div><br />
                <div>
                    <label class="col-md-3"></label>
                    @if ( title == "Create")
                    {
                        <button type="submit" class="btn btn-success">Create</button>
                    }
                    else
                    {
                        <button type="submit" class="btn btn-primary">Update</button>
                    }
                    <a asp-controller="Security" asp-action="Index" class="btn btn-secondary">User List</a>
                </div>              
            </div>
        </div>      
    </form>
</div>

EmailHubApp/Views/Security/AddUpdateUserType.cshtml
@using Microsoft.AspNetCore.Http
@using EmailHubApp.Models;
@model UserTypeOperation
@{
    ViewData["Title"] = "AddUpdateUserType";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger"><strong>Error:&nbsp;</strong>@ViewBag.ErrorMessage</div>
}
@{
    var title = Context.Session.GetString("Title");
}
<h2>@title User-Type</h2>
<hr />
<br />
<div>
    <form method="post" asp-controller="Security" asp-action="AddUpdateUserType">
        <div class="row">
            <div class="col-md-8">
                <div>
                    <label asp-for="Name" class="col-md-3">User Type</label>
                    <input type="text" asp-for="Name" class="col-md-6" required="required" placeholder="Enter User-Type" />
                    <span asp-validation-for="Name" class="text-danger"></span><br />
                    @if (ViewBag.userTypeExists != null)
                    {
                        <label class="col-md-3"></label>
                        <span style="color:red;">@ViewBag.userTypeExists</span>
                    }
                </div><br />

                <div>
                    <label asp-for="Limit" class="col-md-3">Search Limit</label>
                    <input type="text" asp-for="Limit" class="col-md-6" required="required" placeholder="Enter Search Limit" />
                    <span asp-validation-for="Limit" class="text-danger"></span><br />                   
                </div><br />

                <div class="checkbox">
                    <label class="col-md-3"></label>
                    <label>
                        <input type="checkbox" asp-for="IsActive"> Active User Type
                    </label>
                    @if (ViewBag.userTypeActive != null)
                    {
                        <br /><label class="col-md-3"></label>
                        <span style="color:red;">@ViewBag.userTypeActive</span>
                    }
                </div><br />
                <div>
                    <label class="col-md-3"></label>
                    @if (title == "Create")
                    {
                        <button type="submit" class="btn btn-success">Create</button>
                    }
                    else
                    {
                        <button type="submit" class="btn btn-primary">Update</button>
                    }
                    <a asp-controller="Security" asp-action="UserTypeList" class="btn btn-secondary">User Type-List</a>
                </div>
            </div>
        </div>
    </form>
</div>

EmailHubApp/Views/Security/Index.cshtml
@using EmailHubApp.Models;
@model IEnumerable<UserOperation> 

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger"><strong>Error:&nbsp;</strong>@ViewBag.ErrorMessage</div>
}

<h2>User List</h2>
<hr /><a asp-action="AddUpdateUser" class="btn btn-success" style="text-decoration: none;">Create</a>
<br />
<br />
<div>
<table id="example" class="table table-striped nowrap" style="width:100%">
        <thead>
            <tr>
                <th>UserID</th>
                <th>Active Status</th>
                <th>User Name</th>
                <th>User Type</th>
                <th>Total Searched</th>
                <th>Email</th>

                @* <th>Migration Date</th>
                <th>Duration</th> *@

                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach(UserOperation item in Model)
            {
                <tr>
                    <td>@item.UserName</td>
                    <td>@(item.IsActive == true? "Active" : "Inactive")</td>
                    <td>@item.Name</td>
                    <td>
                        @foreach (UserTypeOperation item2 in ViewBag.userType)
                        {
                            if(item2.ID == item.TypeID)
                            {
                                @item2.Name
                                break;
                            }
                        }                       
                    </td>
                    <td>@item.TotalSearched</td>
                    <td>@item.Email</td>
                    @* <td>@item.MembershipStarted</td>
                    <td>@item.MembershipDuration</td> *@
                    <td>
                        <a asp-action="AddUpdateUser" asp-controller="Security" asp-route-id="@item.ID" class="btn btn-outline-warning" style="text-decoration: none"><b>Update</b></a> |
                        <a asp-action="RemoveUser" asp-controller="Security" asp-route-id="@item.ID" class="btn btn-outline-danger" style="text-decoration: none" onclick="return confirm('Are you sure?')"><b>Delete</b></a>
                    </td>
                </tr>
            }           
        </tbody>
    </table>
</div>

EmailHubApp/Views/Security/SearchQueryList.cshtml
@using EmailHubApp.Models;
@{
    ViewData["Title"] = "SearchQueryList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger"><strong>Error:&nbsp;</strong>@ViewBag.ErrorMessage</div>
}
<h2>Search-Query</h2>
<hr /><a asp-action="AddUpdateSearchQuery" class="btn btn-success" style="text-decoration: none;">Create</a>
<br />
<br />
<div>
    <table id="example" class="table table-striped nowrap" style="width:100%">
        <thead>
            <tr>
                <th>Start</th>
                <th>End</th>
                <th>Active Status</th>                
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (SearchQueryOperation item in Model)
            {
                <tr>
                    <td>@item.Start</td>
                    <td>@item.End</td>
                    <td>
                        @if (item.IsActive == false)
                        {
                            <a asp-action="UpdateSearchQueryStatus" asp-controller="Security" asp-route-id="@item.ID" class="btn btn-outline-success" style="text-decoration: none"><b>Active</b></a>
                        }
                        else
                        {
                            <b>Activated</b>
                        }
                    </td>                  
                    <td>
                        <a asp-action="AddUpdateSearchQuery" asp-controller="Security" asp-route-id="@item.ID" class="btn btn-outline-warning" style="text-decoration: none"><b>Update</b></a>                
                        @if (item.IsActive == false)
                        {
                            <span> | </span>
                            <a asp-action="RemoveSearchQuery" asp-controller="Security" asp-route-id="@item.ID" class="btn btn-outline-danger" style="text-decoration: none" onclick="return confirm('Are you sure?')"><b>Delete</b></a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

EmailHubApp/Views/Security/SearchRequirementsList.cshtml
@using EmailHubApp.Models;
@{
    ViewData["Title"] = "SearchRequirementsList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Search-Requirement</h2>
<hr /><a asp-action="AddUpdateSearchRequirements" class="btn btn-success" style="text-decoration: none;">Create</a>
<br />
<br />
<div>
    <table id="example" class="table table-striped nowrap" style="width:100%">
        <thead>
            <tr>
                <th>API Key</th>
                <th>CX</th>
                <th>Search Count</th>
                <th>Searchable(Max 100)</th>
                <th>Active Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (SearchRequirementsOperation item in Model)
            {
                <tr>
                    <td>@item.ApiKey</td>
                    <td>@item.CX</td>
                    <td>@item.SearchCount</td>
                    <td>@(100 - item.SearchCount)</td>
                    <td>@(item.IsActive == true ? "Active" : "Inactive")</td>
                    <td>
                        <a asp-action="AddUpdateSearchRequirements" asp-controller="Security" asp-route-id="@item.ID" class="btn btn-warning" style="text-decoration: none"><b>Update</b></a> |
                        <a asp-action="RemoveSearchRequirements" asp-controller="Security" asp-route-id="@item.ID" class="btn btn-danger" style="text-decoration: none" onclick="return confirm('Are you sure?')"><b>Delete</b></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

EmailHubApp/Views/Security/UserTypeList.cshtml
@using EmailHubApp.Models;
@{
    ViewData["Title"] = "UserTypeList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger"><strong>Error:&nbsp;</strong>@ViewBag.ErrorMessage</div>
}
<h2>User-Type</h2>
<hr /><a asp-action="AddUpdateUserType" class="btn btn-success" style="text-decoration: none;">Create</a>
<br />
<br />
<div>
    <table id="example" class="table table-striped nowrap" style="width:100%">
        <thead>
            <tr>
                <th>User Type</th>               
                <th>Active Status</th>
                <th>Limit</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (UserTypeOperation item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@(item.IsActive == true ? "Active" : "Inactive")</td>
                    <td>@item.Limit</td>
                    <td>
                        <a asp-action="AddUpdateUserType" asp-controller="Security" asp-route-id="@item.ID" class="btn btn-outline-warning" style="text-decoration: none"><b>Update</b></a> |
                        <a asp-action="RemoveUserType" asp-controller="Security" asp-route-id="@item.ID" class="btn btn-outline-danger" style="text-decoration: none" onclick="return confirm('Are you sure?')"><b>Delete</b></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>